import csv

alkali_metals = [
    {
        "Name": "Lithium",
        "Symbol": "Li",
        "Atomic Number": 3,
        "Category": "Alkali Metal",
        "Standard State": "Solid",
        "Crystal Structure": "Body-Centered Cubic (BCC)",
        "Atomic Mass (u)": 6.94,
        "Electronegativity (Pauling)": 0.98,
        "Energy Levels": "2,1",
        "Melting Point (°C)": 180.54,
        "Boiling Point (°C)": 1342,
        "Atomic Radius (pm)": 152,
        "Abundance % (Universe)": 0.0000003,
        "Electron Affinity (eV)": 0.618,
        "Ionization Energy (eV)": 5.3917,
        "Oxidation States": "+1",
        "Protons": 3,
        "Neutrons": 4,
        "Electrons": 3,
        "Electron Configuration": "[He] 2s1",
        "Quantum Numbers (HOAO)": "(2,0,0,1/2)",
        "Discovered": "1817",
        "Light Emission (nm)": "670.8",
    },
    {
        "Name": "Sodium",
        "Symbol": "Na",
        "Atomic Number": 11,
        "Category": "Alkali Metal",
        "Standard State": "Solid",
        "Crystal Structure": "Body-Centered Cubic (BCC)",
        "Atomic Mass (u)": 22.99,
        "Electronegativity (Pauling)": 0.93,
        "Energy Levels": "2,8,1",
        "Melting Point (°C)": 97.72,
        "Boiling Point (°C)": 883,
        "Atomic Radius (pm)": 186,
        "Abundance % (Universe)": 0.002,
        "Electron Affinity (eV)": 0.548,
        "Ionization Energy (eV)": 5.1391,
        "Oxidation States": "+1",
        "Protons": 11,
        "Neutrons": 12,
        "Electrons": 11,
        "Electron Configuration": "[Ne] 3s1",
        "Quantum Numbers (HOAO)": "(3,0,0,1/2)",
        "Discovered": "1807",
        "Light Emission (nm)": "589.0",
    },
    {
        "Name": "Potassium",
        "Symbol": "K",
        "Atomic Number": 19,
        "Category": "Alkali Metal",
        "Standard State": "Solid",
        "Crystal Structure": "Body-Centered Cubic (BCC)",
        "Atomic Mass (u)": 39.10,
        "Electronegativity (Pauling)": 0.82,
        "Energy Levels": "2,8,8,1",
        "Melting Point (°C)": 63.5,
        "Boiling Point (°C)": 759,
        "Atomic Radius (pm)": 227,
        "Abundance % (Universe)": 0.0003,
        "Electron Affinity (eV)": 0.501,
        "Ionization Energy (eV)": 4.3407,
        "Oxidation States": "+1",
        "Protons": 19,
        "Neutrons": 20,
        "Electrons": 19,
        "Electron Configuration": "[Ar] 4s1",
        "Quantum Numbers (HOAO)": "(4,0,0,1/2)",
        "Discovered": "1807",
        "Light Emission (nm)": "766.5, 769.9",
    },
    {
        "Name": "Rubidium",
        "Symbol": "Rb",
        "Atomic Number": 37,
        "Category": "Alkali Metal",
        "Standard State": "Solid",
        "Crystal Structure": "Body-Centered Cubic (BCC)",
        "Atomic Mass (u)": 85.47,
        "Electronegativity (Pauling)": 0.82,
        "Energy Levels": "2,8,18,8,1",
        "Melting Point (°C)": 39.31,
        "Boiling Point (°C)": 688,
        "Atomic Radius (pm)": 248,
        "Abundance % (Universe)": 0.00002,
        "Electron Affinity (eV)": 0.486,
        "Ionization Energy (eV)": 4.1771,
        "Oxidation States": "+1",
        "Protons": 37,
        "Neutrons": 48,
        "Electrons": 37,
        "Electron Configuration": "[Kr] 5s1",
        "Quantum Numbers (HOAO)": "(5,0,0,1/2)",
        "Discovered": "1861",
        "Light Emission (nm)": "780.0, 795.0",
    },
    {
        "Name": "Cesium",
        "Symbol": "Cs",
        "Atomic Number": 55,
        "Category": "Alkali Metal",
        "Standard State": "Solid",
        "Crystal Structure": "Body-Centered Cubic (BCC)",
        "Atomic Mass (u)": 132.91,
        "Electronegativity (Pauling)": 0.79,
        "Energy Levels": "2,8,18,18,8,1",
        "Melting Point (°C)": 28.5,
        "Boiling Point (°C)": 671,
        "Atomic Radius (pm)": 265,
        "Abundance % (Universe)": 0.000003,
        "Electron Affinity (eV)": 0.472,
        "Ionization Energy (eV)": 3.8939,
        "Oxidation States": "+1",
        "Protons": 55,
        "Neutrons": 78,
        "Electrons": 55,
        "Electron Configuration": "[Xe] 6s1",
        "Quantum Numbers (HOAO)": "(6,0,0,1/2)",
        "Discovered": "1860",
        "Light Emission (nm)": "852.1, 894.3",
    },
    {
        "Name": "Francium",
        "Symbol": "Fr",
        "Atomic Number": 87,
        "Category": "Alkali Metal",
        "Standard State": "Solid",
        "Crystal Structure": "Body-Centered Cubic (BCC) (theoretical)",
        "Atomic Mass (u)": 223,
        "Electronegativity (Pauling)": 0.7,
        "Energy Levels": "2,8,18,32,18,8,1",
        "Melting Point (°C)": "27 estimated",
        "Boiling Point (°C)": "677 estimated",
        "Atomic Radius (pm)": 270,
        "Abundance % (Universe)": "Negligible",
        "Electron Affinity (eV)": "0.47 estimated",
        "Ionization Energy (eV)": "3.894 estimated",
        "Oxidation States": "+1",
        "Protons": 87,
        "Neutrons": 136,
        "Electrons": 87,
        "Electron Configuration": "[Rn] 7s1",
        "Quantum Numbers (HOAO)": "(7,0,0,1/2)",
        "Discovered": "1939",
        "Light Emission (nm)": "Uncertain",
    },
]

csv_filename = "alkali_metals.csv"

with open(csv_filename, mode="w", newline="") as file:
    writer = csv.DictWriter(file, fieldnames=alkali_metals[0].keys())
    writer.writeheader()
    writer.writerows(alkali_metals)

csv_filename
