import csv

noble_gases = [
    {
        "Name": "Helium",
        "Symbol": "He",
        "Atomic Number": 2,
        "Category": "Noble Gas",
        "Standard State": "Gas",
        "Crystal Structure": "Hexagonal",
        "Atomic Mass (u)": 4.0026,
        "Electronegativity (Pauling Scale)": "None",
        "Energy Levels": "2",
        "Melting Point (°C)": "None",
        "Boiling Point (°C)": -268.93,
        "Radius (pm)": 31,
        "Abundance % (Universe)": 23,
        "Electron Affinity (eV)": "None",
        "Ionization Energy (eV)": 24.5874,
        "Oxidation States": "0",
        "Protons": 2,
        "Neutrons": 2,
        "Electrons": 2,
        "Electron Configuration": "1s2",
        "Quantum Numbers (HOAO)": "(1,0,0,1/2)",
        "Discovered": "1868",
        "Light Emission (nm)": "447.1, 501.6, 587.6, 667.8",
    },
    {
        "Name": "Neon",
        "Symbol": "Ne",
        "Atomic Number": 10,
        "Category": "Noble Gas",
        "Standard State": "Gas",
        "Crystal Structure": "Cubic",
        "Atomic Mass (u)": 20.180,
        "Electronegativity (Pauling Scale)": "None",
        "Energy Levels": "2,8",
        "Melting Point (°C)": -248.59,
        "Boiling Point (°C)": -246.08,
        "Radius (pm)": 38,
        "Abundance % (Universe)": 0.13,
        "Electron Affinity (eV)": "None",
        "Ionization Energy (eV)": 21.5645,
        "Oxidation States": "0",
        "Protons": 10,
        "Neutrons": 10,
        "Electrons": 10,
        "Electron Configuration": "[He] 2s2 2p6",
        "Quantum Numbers (HOAO)": "(2,1,-1,1/2)",
        "Discovered": "1898",
        "Light Emission (nm)": "540.1, 585.2, 614.3, 640.2",
    },
    {
        "Name": "Argon",
        "Symbol": "Ar",
        "Atomic Number": 18,
        "Category": "Noble Gas",
        "Standard State": "Gas",
        "Crystal Structure": "Cubic",
        "Atomic Mass (u)": 39.948,
        "Electronegativity (Pauling Scale)": "None",
        "Energy Levels": "2,8,8",
        "Melting Point (°C)": -189.34,
        "Boiling Point (°C)": -185.85,
        "Radius (pm)": 71,
        "Abundance % (Universe)": 0.02,
        "Electron Affinity (eV)": "None",
        "Ionization Energy (eV)": 15.7596,
        "Oxidation States": "0",
        "Protons": 18,
        "Neutrons": 22,
        "Electrons": 18,
        "Electron Configuration": "[Ne] 3s2 3p6",
        "Quantum Numbers (HOAO)": "(3,1,-1,1/2)",
        "Discovered": "1894",
        "Light Emission (nm)": "696.5, 706.7, 727.3, 763.5",
    },
    {
        "Name": "Krypton",
        "Symbol": "Kr",
        "Atomic Number": 36,
        "Category": "Noble Gas",
        "Standard State": "Gas",
        "Crystal Structure": "Cubic",
        "Atomic Mass (u)": 83.798,
        "Electronegativity (Pauling Scale)": 3.00,
        "Energy Levels": "2,8,18,8",
        "Melting Point (°C)": -157.36,
        "Boiling Point (°C)": -153.41,
        "Radius (pm)": 88,
        "Abundance % (Universe)": 0.0001,
        "Electron Affinity (eV)": -0.379,
        "Ionization Energy (eV)": 13.9996,
        "Oxidation States": "0, +2",
        "Protons": 36,
        "Neutrons": 48,
        "Electrons": 36,
        "Electron Configuration": "[Ar] 3d10 4s2 4p6",
        "Quantum Numbers (HOAO)": "(4,1,-1,1/2)",
        "Discovered": "1898",
        "Light Emission (nm)": "427.4, 431.9, 556.2, 760.2",
    },
    {
        "Name": "Xenon",
        "Symbol": "Xe",
        "Atomic Number": 54,
        "Category": "Noble Gas",
        "Standard State": "Gas",
        "Crystal Structure": "Cubic",
        "Atomic Mass (u)": 131.293,
        "Electronegativity (Pauling Scale)": 2.60,
        "Energy Levels": "2,8,18,18,8",
        "Melting Point (°C)": -111.8,
        "Boiling Point (°C)": -108.12,
        "Radius (pm)": 108,
        "Abundance % (Universe)": 0.000009,
        "Electron Affinity (eV)": -0.02,
        "Ionization Energy (eV)": 12.1298,
        "Oxidation States": "0, +2, +4, +6",
        "Protons": 54,
        "Neutrons": 77,
        "Electrons": 54,
        "Electron Configuration": "[Kr] 4d10 5s2 5p6",
        "Quantum Numbers (HOAO)": "(5,1,-1,1/2)",
        "Discovered": "1898",
        "Light Emission (nm)": "467.1, 529.2, 823.2, 881.9",
    },
    {
    "Name": "Radon",
    "Symbol": "Rn",
    "Atomic Number": 86,
    "Category": "Noble Gas",
    "Standard State": "Gas",
    "Crystal Structure": "Cubic (theoretical)",
    "Atomic Mass (u)": 222,
    "Electronegativity (Pauling Scale)": 2.2,
    "Energy Levels": "2,8,18,32,18,8",
    "Melting Point (°C)": -71,
    "Boiling Point (°C)": -61.7,
    "Radius (pm)": 120,
    "Abundance % (Universe)": "Negligible",
    "Electron Affinity (eV)": "Not well-defined",
    "Ionization Energy (eV)": 10.7485,
    "Oxidation States": "0, +2, +6",
    "Protons": 86,
    "Neutrons": 136,
    "Electrons": 86,
    "Electron Configuration": "[Xe] 4f14 5d10 6s2 6p6",
    "Quantum Numbers (HOAO)": "(6,1,-1,1/2)",
    "Discovered": "1900",
    "Light Emission (nm)": "Unknown",
    }
]

csv_filename = "noble_gases.csv"

with open(csv_filename, mode="w", newline="") as file:
    writer = csv.DictWriter(file, fieldnames=noble_gases[0].keys())
    writer.writeheader()
    writer.writerows(noble_gases)

print(f"CSV file '{csv_filename}' has been created successfully.")
