import csv

reactive_nonmetals = [
    {
        "Name": "Hydrogen",
        "Symbol": "H",
        "Atomic Number": 1,
        "Category": "Reactive Nonmetal",
        "Standard State": "Gas",
        "Crystal Structure": "Hexagonal",
        "Atomic Mass (u)": 1.008,
        "Electronegativity (Pauling Scale)": 2.20,
        "Energy Levels": "1",
        "Melting Point (°C)": -259.16,
        "Boiling Point (°C)": -252.87,
        "Radius (pm)": 53,
        "Abundance % (Universe)": 75,
        "Electron Affinity (eV)": round(72.8 / 96.485, 3),
        "Ionization Energy (eV)": 13.5984,
        "Oxidation States": "-1, +1",
        "Protons": 1,
        "Neutrons": 0,
        "Electrons": 1,
        "Electron Configuration": "1s1",
        "Quantum Numbers (HOAO)": "(1,0,0,+1/2)",
        "Discovered": "1766",
        "Light Emission (nm)": "656.3, 486.1, 434.0, 410.2",
    },
    {
        "Name": "Carbon",
        "Symbol": "C",
        "Atomic Number": 6,
        "Category": "Reactive Nonmetal",
        "Standard State": "Solid",
        "Crystal Structure": "Hexagonal (Graphite), Diamond Cubic",
        "Atomic Mass (u)": 12.011,
        "Electronegativity (Pauling Scale)": 2.55,
        "Energy Levels": "2,4",
        "Melting Point (°C)": 3550,
        "Boiling Point (°C)": 4027,
        "Radius (pm)": 70,
        "Abundance % (Universe)": 0.5,
        "Electron Affinity (eV)": round(121.8 / 96.485, 3),
        "Ionization Energy (eV)": 11.2603,
        "Oxidation States": "-4, -3, -2, -1, +1, +2, +3, +4",
        "Protons": 6,
        "Neutrons": 6,
        "Electrons": 6,
        "Electron Configuration": "[He] 2s2 2p2",
        "Quantum Numbers (HOAO)": "(2,1,-1,+1/2)",
        "Discovered": "Ancient",
        "Light Emission (nm)": "None",
    },
    {
        "Name": "Nitrogen",
        "Symbol": "N",
        "Atomic Number": 7,
        "Category": "Reactive Nonmetal",
        "Standard State": "Gas",
        "Crystal Structure": "Hexagonal",
        "Atomic Mass (u)": 14.007,
        "Electronegativity (Pauling Scale)": 3.04,
        "Energy Levels": "2,5",
        "Melting Point (°C)": -210.00,
        "Boiling Point (°C)": -195.79,
        "Radius (pm)": 65,
        "Abundance % (Universe)": 0.1,
        "Electron Affinity (eV)": round(-6.8 / 96.485, 3),
        "Ionization Energy (eV)": 14.5341,
        "Oxidation States": "-3, -2, -1, +1, +2, +3, +4, +5",
        "Protons": 7,
        "Neutrons": 7,
        "Electrons": 7,
        "Electron Configuration": "[He] 2s2 2p3",
        "Quantum Numbers (HOAO)": "(2,1,-1,+1/2)",
        "Discovered": "1772",
        "Light Emission (nm)": "149.3",
    },
    {
        "Name": "Oxygen",
        "Symbol": "O",
        "Atomic Number": 8,
        "Category": "Reactive Nonmetal",
        "Standard State": "Gas",
        "Crystal Structure": "Monoclinic",
        "Atomic Mass (u)": 15.999,
        "Electronegativity (Pauling Scale)": 3.44,
        "Energy Levels": "2,6",
        "Melting Point (°C)": -218.79,
        "Boiling Point (°C)": -182.96,
        "Radius (pm)": 60,
        "Abundance % (Universe)": 1,
        "Electron Affinity (eV)": round(140.0 / 96.485, 3),
        "Ionization Energy (eV)": 13.6181,
        "Oxidation States": "-2, -1, +1, +2",
        "Protons": 8,
        "Neutrons": 8,
        "Electrons": 8,
        "Electron Configuration": "[He] 2s2 2p4",
        "Quantum Numbers (HOAO)": "(2,1,-1,+1/2)",
        "Discovered": "1774",
        "Light Emission (nm)": "130.2",
    },
    {
        "Name": "Fluorine",
        "Symbol": "F",
        "Atomic Number": 9,
        "Category": "Reactive Nonmetal",
        "Standard State": "Gas",
        "Crystal Structure": "Cubic",
        "Atomic Mass (u)": 18.998,
        "Electronegativity (Pauling Scale)": 3.98,
        "Energy Levels": "2,7",
        "Melting Point (°C)": -219.67,
        "Boiling Point (°C)": -188.11,
        "Radius (pm)": 50,
        "Abundance % (Universe)": 0.00004,
        "Electron Affinity (eV)": round(328.2 / 96.485, 3),
        "Ionization Energy (eV)": 17.4228,
        "Oxidation States": "-1",
        "Protons": 9,
        "Neutrons": 10,
        "Electrons": 9,
        "Electron Configuration": "[He] 2s2 2p5",
        "Quantum Numbers (HOAO)": "(2,1,-1,+1/2)",
        "Discovered": "1886",
        "Light Emission (nm)": "None",
    },
    {
        "Name": "Phosphorus",
        "Symbol": "P",
        "Atomic Number": 15,
        "Category": "Reactive Nonmetal",
        "Standard State": "Solid",
        "Crystal Structure": "Orthorhombic",
        "Atomic Mass (u)": 30.973,
        "Electronegativity (Pauling Scale)": 2.19,
        "Energy Levels": "2,8,5",
        "Melting Point (°C)": "44.15 white phosphorus",
        "Boiling Point (°C)": "280.5 white phosphorus",
        "Radius (pm)": 98,
        "Abundance % (Universe)": 0.0007,
        "Electron Affinity (eV)": 72.0,
        "Ionization Energy (eV)": 10.4867,
        "Oxidation States": "-3, +1, +3, +5",
        "Protons": 15,
        "Neutrons": 16,
        "Electrons": 15,
        "Electron Configuration": "[Ne] 3s2 3p3",
        "Quantum Numbers (HOAO)": "(3,1,-1,1/2)",
        "Discovered": "1669",
        "Light Emission (nm)": "None",
    },
    {
        "Name": "Sulfur",
        "Symbol": "S",
        "Atomic Number": 16,
        "Category": "Reactive Nonmetal",
        "Standard State": "Solid",
        "Crystal Structure": "Orthorhombic",
        "Atomic Mass (u)": 32.06,
        "Electronegativity (Pauling Scale)": 2.58,
        "Energy Levels": "2,8,6",
        "Melting Point (°C)": 115.21,
        "Boiling Point (°C)": 444.6,
        "Radius (pm)": 88,
        "Abundance % (Universe)": 0.05,
        "Electron Affinity (eV)": 200.4,
        "Ionization Energy (eV)": 10.36,
        "Oxidation States": "-2, +2, +4, +6",
        "Protons": 16,
        "Neutrons": 16,
        "Electrons": 16,
        "Electron Configuration": "[Ne] 3s2 3p4",
        "Quantum Numbers (HOAO)": "(3,1,-1,1/2)",
        "Discovered": "Ancient",
        "Light Emission (nm)": "None",
    },
    {
        "Name": "Chlorine",
        "Symbol": "Cl",
        "Atomic Number": 17,
        "Category": "Reactive Nonmetal",
        "Standard State": "Gas",
        "Crystal Structure": "Orthorhombic",
        "Atomic Mass (u)": 35.45,
        "Electronegativity (Pauling Scale)": 3.16,
        "Energy Levels": "2,8,7",
        "Melting Point (°C)": -101.5,
        "Boiling Point (°C)": -34.04,
        "Radius (pm)": 79,
        "Abundance % (Universe)": 0.0001,
        "Electron Affinity (eV)": 349.0,
        "Ionization Energy (eV)": 12.9676,
        "Oxidation States": "-1, +1, +3, +5, +7",
        "Protons": 17,
        "Neutrons": 18,
        "Electrons": 17,
        "Electron Configuration": "[Ne] 3s2 3p5",
        "Quantum Numbers (HOAO)": "(3,1,-1,1/2)",
        "Discovered": "1774",
        "Light Emission (nm)": "139.4, 135.2",
    },
    {
        "Name": "Selenium",
        "Symbol": "Se",
        "Atomic Number": 34,
        "Category": "Reactive Nonmetal",
        "Standard State": "Solid",
        "Crystal Structure": "Hexagonal",
        "Atomic Mass (u)": 78.971,
        "Electronegativity (Pauling Scale)": 2.55,
        "Energy Levels": "2,8,18,6",
        "Melting Point (°C)": 221,
        "Boiling Point (°C)": 685,
        "Radius (pm)": 103,
        "Abundance % (Universe)": 0.00003,
        "Electron Affinity (eV)": 195.0,
        "Ionization Energy (eV)": 9.7524,
        "Oxidation States": "-2, +2, +4, +6",
        "Protons": 34,
        "Neutrons": 45,
        "Electrons": 34,
        "Electron Configuration": "[Ar] 3d10 4s2 4p4",
        "Quantum Numbers (HOAO)": "(4,1,-1,1/2)",
        "Discovered": "1817",
        "Light Emission (nm)": "None",
    },
    {
        "Name": "Bromine",
        "Symbol": "Br",
        "Atomic Number": 35,
        "Category": "Reactive Nonmetal",
        "Standard State": "Liquid",
        "Crystal Structure": "Orthorhombic",
        "Atomic Mass (u)": 79.904,
        "Electronegativity (Pauling Scale)": 2.96,
        "Energy Levels": "2,8,18,7",
        "Melting Point (°C)": -7.2,
        "Boiling Point (°C)": 58.8,
        "Radius (pm)": 94,
        "Abundance % (Universe)": 0.00002,
        "Electron Affinity (eV)": 324.5,
        "Ionization Energy (eV)": 11.8138,
        "Oxidation States": "-1, +1, +3, +5, +7",
        "Protons": 35,
        "Neutrons": 45,
        "Electrons": 35,
        "Electron Configuration": "[Ar] 3d10 4s2 4p5",
        "Quantum Numbers (HOAO)": "(4,1,-1,1/2)",
        "Discovered": "1826",
        "Light Emission (nm)": "206.2, 266.7",
    },
    {
        "Name": "Iodine",
        "Symbol": "I",
        "Atomic Number": 53,
        "Category": "Reactive Nonmetal",
        "Standard State": "Solid",
        "Crystal Structure": "Orthorhombic",
        "Atomic Mass (u)": 126.90,
        "Electronegativity (Pauling Scale)": 2.66,
        "Energy Levels": "2,8,18,18,7",
        "Melting Point (°C)": 113.7,
        "Boiling Point (°C)": 184.3,
        "Radius (pm)": 115,
        "Abundance % (Universe)": 0.0000001,
        "Electron Affinity (eV)": 295.2,
        "Ionization Energy (eV)": 10.4513,
        "Oxidation States": "-1, +1, +3, +5, +7",
        "Protons": 53,
        "Neutrons": 74,
        "Electrons": 53,
        "Electron Configuration": "[Kr] 4d10 5s2 5p5",
        "Quantum Numbers (HOAO)": "(5,1,-1,1/2)",
        "Discovered": "1811",
        "Light Emission (nm)": "206.2, 342.0",
    }
]

csv_filename = "reactive_nonmetals.csv"

with open(csv_filename, mode="w", newline="") as file:
    writer = csv.DictWriter(file, fieldnames=reactive_nonmetals[0].keys())
    writer.writeheader()
    writer.writerows(reactive_nonmetals)

print(f"CSV file '{csv_filename}' has been created successfully.")
