import csv

reactive_nonmetals = [
    {
        "Name": "Hydrogen",
        "Symbol": "H",
        "Atomic Number": 1,
        "Category": "Reactive Nonmetal",
        "Standard State": "Gas",
        "Crystal Structure": "Hexagonal",
        "Atomic Mass (u)": 1.008,
        "Electronegativity (Pauling Scale)": 2.20,
        "Energy Levels": "1",
        "Melting Point (°C)": -259.16,
        "Boiling Point (°C)": -252.87,
        "Radius (pm)": 53,
        "Abundance % (Universe)": 75,
        "Electron Affinity (eV)": round(72.8 / 96.485, 3),
        "Ionization Energy (eV)": 13.5984,
        "Oxidation States": "-1, +1",
        "Protons": 1,
        "Neutrons": 0,
        "Electrons": 1,
        "Electron Configuration": "1s1",
        "Quantum Numbers (HOAO)": "(1,0,0,+1/2)",
        "Discovered": "1766",
        "Light Emission (nm)": "656.3, 486.1, 434.0, 410.2",
    },
    {
        "Name": "Carbon",
        "Symbol": "C",
        "Atomic Number": 6,
        "Category": "Reactive Nonmetal",
        "Standard State": "Solid",
        "Crystal Structure": "Hexagonal (Graphite), Diamond Cubic",
        "Atomic Mass (u)": 12.011,
        "Electronegativity (Pauling Scale)": 2.55,
        "Energy Levels": "2,4",
        "Melting Point (°C)": 3550,
        "Boiling Point (°C)": 4027,
        "Radius (pm)": 70,
        "Abundance % (Universe)": 0.5,
        "Electron Affinity (eV)": round(121.8 / 96.485, 3),
        "Ionization Energy (eV)": 11.2603,
        "Oxidation States": "-4, -3, -2, -1, +1, +2, +3, +4",
        "Protons": 6,
        "Neutrons": 6,
        "Electrons": 6,
        "Electron Configuration": "[He] 2s2 2p2",
        "Quantum Numbers (HOAO)": "(2,1,-1,+1/2)",
        "Discovered": "Ancient",
        "Light Emission (nm)": "None",
    },
    {
        "Name": "Nitrogen",
        "Symbol": "N",
        "Atomic Number": 7,
        "Category": "Reactive Nonmetal",
        "Standard State": "Gas",
        "Crystal Structure": "Hexagonal",
        "Atomic Mass (u)": 14.007,
        "Electronegativity (Pauling Scale)": 3.04,
        "Energy Levels": "2,5",
        "Melting Point (°C)": -210.00,
        "Boiling Point (°C)": -195.79,
        "Radius (pm)": 65,
        "Abundance % (Universe)": 0.1,
        "Electron Affinity (eV)": round(-6.8 / 96.485, 3),
        "Ionization Energy (eV)": 14.5341,
        "Oxidation States": "-3, -2, -1, +1, +2, +3, +4, +5",
        "Protons": 7,
        "Neutrons": 7,
        "Electrons": 7,
        "Electron Configuration": "[He] 2s2 2p3",
        "Quantum Numbers (HOAO)": "(2,1,-1,+1/2)",
        "Discovered": "1772",
        "Light Emission (nm)": "149.3",
    },
    {
        "Name": "Oxygen",
        "Symbol": "O",
        "Atomic Number": 8,
        "Category": "Reactive Nonmetal",
        "Standard State": "Gas",
        "Crystal Structure": "Monoclinic",
        "Atomic Mass (u)": 15.999,
        "Electronegativity (Pauling Scale)": 3.44,
        "Energy Levels": "2,6",
        "Melting Point (°C)": -218.79,
        "Boiling Point (°C)": -182.96,
        "Radius (pm)": 60,
        "Abundance % (Universe)": 1,
        "Electron Affinity (eV)": round(140.0 / 96.485, 3),
        "Ionization Energy (eV)": 13.6181,
        "Oxidation States": "-2, -1, +1, +2",
        "Protons": 8,
        "Neutrons": 8,
        "Electrons": 8,
        "Electron Configuration": "[He] 2s2 2p4",
        "Quantum Numbers (HOAO)": "(2,1,-1,+1/2)",
        "Discovered": "1774",
        "Light Emission (nm)": "130.2",
    },
    {
        "Name": "Fluorine",
        "Symbol": "F",
        "Atomic Number": 9,
        "Category": "Reactive Nonmetal",
        "Standard State": "Gas",
        "Crystal Structure": "Cubic",
        "Atomic Mass (u)": 18.998,
        "Electronegativity (Pauling Scale)": 3.98,
        "Energy Levels": "2,7",
        "Melting Point (°C)": -219.67,
        "Boiling Point (°C)": -188.11,
        "Radius (pm)": 50,
        "Abundance % (Universe)": 0.00004,
        "Electron Affinity (eV)": round(328.2 / 96.485, 3),
        "Ionization Energy (eV)": 17.4228,
        "Oxidation States": "-1",
        "Protons": 9,
        "Neutrons": 10,
        "Electrons": 9,
        "Electron Configuration": "[He] 2s2 2p5",
        "Quantum Numbers (HOAO)": "(2,1,-1,+1/2)",
        "Discovered": "1886",
        "Light Emission (nm)": "None",
    },
]

csv_filename = "reactive_nonmetals.csv"

with open(csv_filename, mode="w", newline="") as file:
    writer = csv.DictWriter(file, fieldnames=reactive_nonmetals[0].keys())
    writer.writeheader()
    writer.writerows(reactive_nonmetals)

print(f"CSV file '{csv_filename}' has been created successfully.")
